version: "3.0"
   
services:
  db:
    image: postgres
    environment:
        POSTGRES_DB: "db"
        POSTGRES_HOST_AUTH_METHOD: "trust"
    volumes:
      - ./data/db:/var/lib/postgresql/data
    expose:
      - "5433"
    ports:
      - "5433:5433"
    command: 
      -p 5433
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8001
    volumes:
      - .:/code
    ports:
      - "8001:8001"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db
